# Generated by Django 3.0.4 on 2020-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200315_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Rascunho'), (1, 'Publicado')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(max_length=128, verbose_name='URL'),
        ),
    ]
